name: Advent of Code checks

on:
  - push
  - pull_request

jobs:
  test-advent-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5
      - run: go test ./...
      - run: go run ./cmd/solver/main.go 2023 all
#      - run: go run ./cmd/solver/main.go 2024 all
      - run: git diff
