name: Advent of Code checks

on:
  - push
  - pull_request

jobs:
  test-advent-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5
      - run: go test ./y2023/...
      - run: go run ./cmd/solver/main.go y2023 all
      - run: git status
