name: Checks of Python code

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/python.yml'

jobs:

  test-py-advent-of-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: uv sync
      - name: Lint with ruff
        run: uv run ruff check .
      - name: Check formatting with ruff
        run: uv run ruff format --check .
      - name: Run tests
        run: uv run pytest .
        env:
          PYTHONPATH: .
      - run: git diff
